### ISSUE TITLE
Title Missing after Next Chapter

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/uw-android#28]
If you go to story 9, slide through it and then click Next Chapter the title for story 10 will not appear in the top bar.  Same problem in English and Russian & on 2 devces.

**Comment by bknatterud** [comment]
I see it. Looks like it is just chapter 9. I'm thinking maybe a JSON issue. Checking on it now....

**Comment by jag3773** [comment]
Can't be a JSON issue because if you click straight to story 9 then the title shows up properly.
