### ISSUE TITLE
Shrink Title Font Size to Fit Title

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/uw-android#29]
On smaller devices it appears that the title is being cut off in portrait mode when viewing a story.  If you have a small phone to test on then Story 8 in Russian should exhibit this issue.  Can we shrink the font size in the top bar so that it fits properly?

**Comment by bknatterud** [comment]
There will invariably be some devices that can't fit the entire title test. We can shrink, but at some point text will get cut off if the title is too large and device is too small.

How much smaller do you want it?

**Comment by jag3773** [comment]
I mean dynamically shrink the text, is that possible?  If not, can you set the size based on screen size?

**Comment by bknatterud** [comment]
Ok, yes we can do it that way. Sorry, I thought you meant for all devices.
