### ISSUE TITLE
Crashes on attempted open

### ISSUE THREAD

**Issue by kjhaugh** [unfoldingWord/uw-android#37]
Jesse Griffin may have notified you already about this but my unfoldingWord program on the Nexus 7 crashed upon an attempted open. It then opens a dialog box offering to submit a bug report. I have submitted one on the tablet. 
The tablet is Nexus 7, Andriod version 5.0.2, Kernel Version 3.4.0-g154bef4, Build number LRX22G

**Comment by bknatterud** [comment]
This is related to issue #38 . Version 2.0.3 should fix this issue.
