### ISSUE TITLE
Caching Issue with Last Frame

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/uw-android#39]
Related to #27, when updated from 2.0.1 to 2.0.2 the last frame issue is not fixed until the cache for a given story is somehow cleared.  It seems like going through the story in a new language fixes it, or also hitting the next button to go to the next story but then backing out and going back through the previous story.

In either case, for people with 2.0.1 already installed the issue of #27 is not really resolved.

**Comment by bknatterud** [comment]
fixed, uploading build soon
