### ISSUE TITLE
Check Crash Reports in Play Store

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/uw-android#44]

**Comment by bknatterud** [comment]
build 2.0.4 fixes this issue

**Comment by melvilje** [comment]
Sorry for the redundancy. Christine Jarka and I were testing tS this morning and switching keyboards and I encountered the problem. I was aware of the update to tK, but it has not made it to my tablet yet. I will install the latest version. Thanks.

**Comment by bknatterud** [comment]
is this crash report for unfoldingWord, translationKeyboard or translationStudio?

**Comment by melvilje** [comment]
Another 'opps'. I had just crashed tK this morning and then saw the note about uW and impulsively commented on the wrong issue. Sorry!
